# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : simple site
author :
  name : Maylis Avaro
  email : maylis.avaro@iheid.ch
# github : kbroman
  twitter : M_Avaro
# feedburner : nil

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
#production_url : http://kbroman.github.io/simple_site

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0
